# Generated by Django 6.1 on 2026-09-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chants', '0002_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='profil',
            new_name='profil_image',
        ),
    ]
